
# CLI tool, only in development environment.
# https://goframe.org/pages/viewpage.action?pageId=3673173
gfcli:
  docker:
    build: "-a amd64 -s linux -p temp -ew"
    tagPrefixes:
      - my.image.pub/my-app

  gen:
    dao:
    - link:  "mysql:homestead:secret@tcp(192.168.56.56:3306)/go-simple-admin"
      tables: "users,user_extends"