// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"goSimpleAdmin/internal/dao/internal"
)

// internalUserExtendsDao is internal type for wrapping internal DAO implements.
type internalUserExtendsDao = *internal.UserExtendsDao

// userExtendsDao is the data access object for table user_extends.
// You can define custom methods on it to extend its functionality as you wish.
type userExtendsDao struct {
	internalUserExtendsDao
}

var (
	// UserExtends is globally public accessible object for table user_extends operations.
	UserExtends = userExtendsDao{
		internal.NewUserExtendsDao(),
	}
)

// Fill with you ideas below.
